# Generated by Django 4.2 on 2024-01-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_invite_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="telegram invite"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="chat_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="telegram chat id"
            ),
        ),
    ]
