# Generated by Django 5.0 on 2023-12-29 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=155, verbose_name="место")),
                ("action", models.CharField(max_length=155, verbose_name="действие")),
                ("schedule", models.DateField(verbose_name="время")),
                ("is_pleasant", models.BooleanField(verbose_name="приятная")),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="периодичность (дни)"
                    ),
                ),
                ("reward", models.CharField(max_length=255, verbose_name="награда")),
                ("duration", models.DurationField(verbose_name="продолжительность")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="публичная"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                        verbose_name="связана",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
