# Generated by Django 5.0 on 2023-12-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="schedule",
            field=models.DateTimeField(verbose_name="время"),
        ),
    ]
