# Generated by Django 5.0 on 2024-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="отправлено"
            ),
        ),
    ]
