# Generated by Django 5.0 on 2024-01-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_last_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="schedule",
            field=models.TimeField(verbose_name="время"),
        ),
    ]
