# Generated by Django 4.2 on 2024-01-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habit_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="schedule",
            field=models.TimeField(blank=True, null=True, verbose_name="время"),
        ),
    ]
